version: '2.4'

services:

  mongodb:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  app:
    build:
      context: ./
      args:
        - NODE_ENV=development
      # target: dev
      target: test

    ports:
      - "80:3000"
      # debug port
      - "9229:9229"
    volumes:
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - mongodb

volumes:
  data:


